function downloadPDF(){
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const message = document.getElementById("inputText").value || "N/A";
  const note = document.getElementById("victimNote").value || "Not provided";
  const time = new Date().toLocaleString();
  const caseId = "CASE-" + Math.floor(Math.random()*100000);

  doc.setFontSize(18);
  doc.text("SDM PRO MAX - Cyber Crime Evidence Report", 14, 20);

  doc.setFontSize(11);
  doc.text("Case ID: " + caseId, 14, 35);
  doc.text("Date & Time: " + time, 14, 42);

  doc.line(14, 45, 195, 45);

  doc.setFontSize(13);
  doc.text("Incident Message:", 14, 55);
  doc.setFontSize(10);
  doc.text(message.substring(0, 800), 14, 62, { maxWidth: 180 });

  doc.setFontSize(13);
  doc.text("Victim Statement:", 14, 100);
  doc.setFontSize(10);
  doc.text(note.substring(0, 500), 14, 107, { maxWidth: 180 });

  doc.setFontSize(13);
  doc.text("AI Analysis Result:", 14, 145);
  doc.setFontSize(10);
  doc.text(
    "• Risk Level: Auto-Detected\n• Crime Category: Cyber Fraud / Sextortion\n• System: AI-Assisted (Final decision by authority)",
    14, 152
  );

  doc.setFontSize(9);
  doc.text(
    "Disclaimer: This report is generated by an AI-assisted system. "
    + "Final verification must be done by law enforcement authorities.",
    14, 185,
    { maxWidth: 180 }
  );

  doc.save(caseId + "_Evidence_Report.pdf");
}